sudo: required
services:
    - docker

before_install: 
    - docker build -t vsprakash2003/react-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vsprakash2003/react-docker-test yarn test

after_success:
    - docker build -t vsprakash2003/docker-multi-container-client-test:v1 ./client
    - docker build -t vsprakash2003/docker-multi-container-nginx-test:v1 ./nginx
    - docker build -t vsprakash2003/docker-multi-container-server-test:v1 ./server
    - docker build -t vsprakash2003/docker-multi-container-worker-test:v1 ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vsprakash2003/docker-multi-container-client-test:v1
    - docker push vsprakash2003/docker-multi-container-nginx-test:v1
    - docker push vsprakash2003/docker-multi-container-server-test:v1
    - docker push vsprakash2003/docker-multi-container-worker-test:v1

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker-test
    env: MultiDockerTest-env
    bucket_name: elasticbeanstalk-us-east-2-878765816605
    bucket_path: docker_multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY