sudo: required
services:
    - docker

before_install: 
    - docker build -t vsprakash2003/react-docker-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vsprakash2003/react-docker-test yarn test

after_success:
    - docker build -t vsprakash2003/docker-multi-client-test ./client
    - docker build -t vsprakash2003/docker-multi-nginx-test ./nginx
    - docker build -t vsprakash2003/docker-multi-server-test ./server
    - docker build -t vsprakash2003/docker-multi-worker-test ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vsprakash2003/docker-multi-client-test
    - docker push vsprakash2003/docker-multi-nginx-test
    - docker push vsprakash2003/docker-multi-server-test
    - docker push vsprakash2003/docker-multi-worker-test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker-test
    env: MultiDockerTest-env
    bucket_name: elasticbeanstalk-us-east-2-878765816605
    bucket_path: docker_multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY